[package]
name = "bevy_log_events"
version = "0.1.0"
edition = "2021"
description = "A Bevy plugin that log events"
repository = ""
license = "MIT OR Apache-2.0"
keywords = ["bevy"]
categories = ["game-development"]
exclude = ["assets/", "examples/"]
readme = "README.md"

[features]
default = []
editor_window = ["dep:bevy_editor_pls", "dep:regex"]

[dependencies]
bevy = { version = "0.13", default-features = false }
bevy_editor_pls = { version = "0.8", optional = true }
regex = { version = "1", optional = true }
ron = "0.8"
serde = "1.0"

[dev-dependencies]
bevy = "0.13"
bevy_editor_pls = "0.8"
rand = "0.8.5"

[[example]]
name = "simple"
path = "examples/simple.rs"

[[example]]
name = "window"
path = "examples/window.rs"
required-features = ["editor_window"]
